version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000' # Adjust to your app's port
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - DOMAIN=${DOMAIN}
      - DB_SSL_CA=${DB_SSL_CA}
      - NODE_ENV=${NODE_ENV:-production}
    env_file:
      - .env
    restart: unless-stopped
